name: Go

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      
    - name: RUN
      run: go run main.go
      
