name: juejin

on:
  schedule:
    - cron: '0 2 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      
    - name: RUN
      env:
        FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
        COOKIE: ${{ secrets.COOKIE }}
      run: go run main.go
      
